### ISSUE TITLE
Callbacks are not fired on android

### ISSUE THREAD

**Issue by patrickwitter** [codenameakshay/secure_content#1]
**Describe the bug**
 onScreenshotCaptured:
  onScreenRecordingStart:
  onScreenRecordingStop:
  
  These callbacks are not fired when the event occurs
  

**To Reproduce**

1. Use the example app
2. run the application
3. Start Screen Recording 

**Expected behavior**
A toast to be shown 

No toast is shown.

**Flutter:**

- version
- 3.10
- channel

**Dart:**

- version

**Additional context**

**Comment by codenameakshay** [comment]
Okay, I am checking this, and upgrading to support latest Flutter version as well.

**Comment by codenameakshay** [comment]
Hey, I checked and found out that the callbacks are not really needed on Android. As the package automatically blocks any screenshot (and shows a toast when user tries to click it) and screen recording (it automatically blackens the video). Also the package I was using to make this accomplish is not updated since last year.
These callbacks are necessary on iOS (as user can still record the screen, so you can show warning or any other alert message), but on Android they don't make sense for now. So I will be closing this issue, and request you to check the `0.1.0` version of the package, as it updated to latest Flutter, and is working on both Android & iOS.

Thanks for using `secure_content` package.
